[workspace]
members = [
    "crates/teleark-core",
    "crates/teleark-crypto",
    "crates/teleark-i18n",
    "crates/teleark-gui",
    "crates/teleark-index",
    "crates/teleark-runtime",
    "crates/teleark-storage",
    "crates/teleark-telegram",
    "crates/teleark-transfer",
]
resolver = "2"

[workspace.package]
version = "0.5.5"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/teleark/teleark"
rust-version = "1.88"

[workspace.dependencies]
gpui-kit = "=0.6.0"
teleark-core = { version = "=0.5.5", path = "crates/teleark-core" }
teleark-crypto = { version = "=0.5.5", path = "crates/teleark-crypto" }
teleark-i18n = { version = "=0.5.5", path = "crates/teleark-i18n" }
teleark-index = { version = "=0.5.5", path = "crates/teleark-index" }
teleark-runtime = { version = "=0.5.5", path = "crates/teleark-runtime" }
teleark-storage = { version = "=0.5.5", path = "crates/teleark-storage" }
teleark-telegram = { version = "=0.5.5", path = "crates/teleark-telegram" }
teleark-transfer = { version = "=0.5.5", path = "crates/teleark-transfer" }
tracing = "=0.1.44"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"

[profile.dev.package]
gpui-pre = { opt-level = 3 }
gpui-pre-macos = { opt-level = 3 }
taffy = { opt-level = 3 }
rustybuzz = { opt-level = 3 }
ttf-parser = { opt-level = 3 }
